extends:
  - google
  - plugin:prettier/recommended
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/no-object-literal-type-assertion': 0
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/indent': 0
  prettier/prettier:
    - error
    - endOfLine: lf
      singleQuote: true
      trailingComma: all
  require-jsdoc: 0

  # ToDo
  new-cap: 0
overrides:
  - files: tests
    env:
      mocha: true
